---
- name: Obtener versión de Linux usando facts
  hosts: all
  tasks:
    - name: Mostrar versión de Linux
      debug:
        msg: "La versión de Linux es {{ ansible_distribution }} {{ ansible_distribution_version }}"
